server:
  port: 1115
mybatis:
  config-location: classpath:mybatis-config.xml
spring:
  application:
      name: usercenter
  aop:
      auto: true
      proxy-target-class: false
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.10.80:3306/test?useSSL=false
      username: root
      password: tourongjia123!
      testOnBorrow: true
      testWhileIdle: true
      validationQuery: select 1
pagehelper:
  autoDialect: true
  closeConn: false
  reasonable: true
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:1114/eureka/
beetl:
  suffix: html
beetlsql:
  dbStyle: org.beetl.sql.core.db.MySqlStyle
  basePackage: com.trj.usercenter


