server:
  port: 8000
mybatis:
  config-location: classpath:mybatis-config.xml
spring:
  aop:
      auto: true
      proxy-target-class: false
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.10.80:3306/test?useSSL=false
      username: root
      password: tourongjia123!
      testOnBorrow: true
      testWhileIdle: true
      validationQuery: select 1
pagehelper:
  autoDialect: true
  closeConn: false
  reasonable: true


